### ISSUE TITLE
Definir as cores do site

### ISSUE THREAD

**Issue by vitor-sld** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-expresso-virtual#5]

**Comment by josef-f** [comment]
![Image](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-expresso-virtual/assets/144382841/8eaeef35-41f6-41a3-9710-b90c1a32d493)
