### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by Souzaa86** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-expresso-virtual#60]

**Comment by laura-lannab** [comment]
- [ ] consertar RF e RNF(em Especificação do Projeto está numerado de uma forma e em Programação de Funcionalidades de outra)
- [ ] mais testes
- [ ] revisar numeração das figuras
- [ ] criar slide de apresentação
- [ ] criar video de apresentação
