### ISSUE TITLE
Arquivo de inspiração

### ISSUE THREAD

**Issue by vitor-sld** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-expresso-virtual#7]

**Comment by vitor-sld** [comment]
Colar imagens dentro de um arquivo word como se fosse colagem de fotos:

https://www.behance.net/gallery/177005923/E-commerce-Website-Coffee-Shop?tracking_source=search_projects|coffee+website

https://www.behance.net/gallery/177256777/Starbucks-Coffee-shop-website-design?tracking_source=search_projects|coffee+website

https://www.behance.net/gallery/161520927/CoffeeWebsite-of-coffee-house?tracking_source=search_projects|coffee+website

https://www.behance.net/gallery/177076131/Coffee-Website?tracking_source=search_projects|coffee+website

https://www.behance.net/gallery/170913409/Coffee-Shop-Website-Design?tracking_source=search_projects|coffee+website

https://www.behance.net/gallery/170637767/Coffee-Shop-Website?tracking_source=search_projects|coffee+website

https://rocket-espresso.com/super-fausto-grinder.html

https://fonts.google.com/specimen/Poppins

mandar cores

**Comment by Souzaa86** [comment]
[arquivo inspiração.docx](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-expresso-virtual/files/12674595/arquivo.inspiracao.docx)
